//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GmailScraper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("label:\"Order Confirmation\" subject:\"Charity Gift Certificates\" Donation OH item I" +
            "D: 2020 ")]
        public string LastSearch {
            get {
                return ((string)(this["LastSearch"]));
            }
            set {
                this["LastSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[{""Required"":true,""Name"":""OrderId"",""Regex"":""Invoice ID:.+?(\\d+)"",""GroupNumber"":1},{""Required"":false,""Name"":""GrandTotal"",""Regex"":""Grand Total:.+?\\$([\\d\\.,]+)"",""GroupNumber"":1},{""Required"":false,""Name"":""CharityDonations"",""Regex"":""Total for Charity Donations:.+?\\$([\\d\\.,]+)"",""GroupNumber"":1},{""Required"":false,""Name"":""Tip SKF"",""Regex"":""Total tip for Special Kids:.+?\\$([\\d\\.,]+)"",""GroupNumber"":1},{""Required"":false,""Name"":""CharityCards"",""Regex"":""Total for Charity Cards:.+?\\$([\\d\\.,]+)"",""GroupNumber"":1},{""Required"":false,""Name"":""Physical cards"",""Regex"":""Total for Physical Cards:.+?\\$([\\d\\.,]+)"",""GroupNumber"":1},{""Required"":false,""Name"":""Redemption Codes"",""Regex"":""Total for Redemption Codes:.+?\\$([\\d\\.,]+)"",""GroupNumber"":1},{""Required"":false,""Name"":""Shipping"",""Regex"":""Shipping \\& Handling:.+?\\$([\\d\\.,]+)"",""GroupNumber"":1}]
")]
        public string FieldsToFind {
            get {
                return ((string)(this["FieldsToFind"]));
            }
            set {
                this["FieldsToFind"] = value;
            }
        }
    }
}
